In [ ]:
import csv
import random
import numpy as np

Creation of data

In [ ]:
# Create a 10x9 matrix with random values between 1 and 100
data = np.random.randint(1, 101, size=(10, 9))

In [ ]:
# Create random weights
weights = np.random.rand(9)

In [ ]:
# Calculate the last column as a linear combination of the other columns
last_column = np.dot(data, weights)

In [ ]:
# Add the last column to the data
data = np.column_stack((data, last_column))

In [ ]:
# Write the data to a CSV file
with open('linear_regression_data.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

In [ ]:
print("CSV file 'linear_regression_data.csv' with linear regression data has been created.")
print(weights)

CSV file 'linear_regression_data.csv' with linear regression data has been created.
[0.25898673 0.52988319 0.96062612 0.86282804 0.52380716 0.21911974
 0.77928876 0.62658374 0.81519617]


Linear Regression(9 Features)

In [19]:
# Gradient Descent Algorithm
def gradientDecent(X,Y,weights,bias,epochs,alpha,num):
    for i in range(epochs):
        prediction = X.dot(weights.T) + bias
        prediction = np.asarray(prediction)
        error = prediction - Y.T
        error = np.asarray(error)
        temp = np.divide(np.multiply(alpha,error.T.dot(X)),num)#to avoid error from numpy
        weights = np.subtract(weights, temp)
        bias = bias - (alpha * np.sum(error))/num
    return weights,bias

In [71]:
# Hyperparamenters
alpha = 0.000001
epochs = 10000


In [72]:
# Assigning random weights and bias
weights = np.random.randint(1,100,(1,9))
bias = np.random.randint(1,100)

In [15]:
# Load the data from the CSV file into a numpy array
data = np.genfromtxt('linear_regression_data.csv', delimiter=',')
Y = data[:,-1].copy()
Y = Y.reshape(1,10)
X = np.delete(data, -1, axis=1)

In [73]:
X,Y

(array([[38., 84.,  2., 90., 32., 66., 81.,  6., 56.],
        [98., 83., 61., 49., 18., 63.,  7., 20.,  8.],
        [90., 27., 15., 76.,  8., 38., 40., 18., 69.],
        [69., 34., 66.,  4., 39., 25., 41., 27., 84.],
        [86., 95., 78., 46., 96., 90.,  6., 44., 90.],
        [49., 20., 92.,  7., 33., 14., 68., 32., 49.],
        [56., 27., 13., 42., 21.,  8., 95., 62., 73.],
        [66., 69., 27., 20., 21., 55., 37., 25., 14.],
        [28., 43., 90., 90., 94., 89., 71., 80., 78.],
        [63., 42., 57., 70., 18., 49., 26., 15.,  7.]]),
 array([[277.68406809, 217.97910861, 228.81557461, 245.99029936,
         362.85002373, 251.04565296, 262.6798725 , 175.81108974,
         431.92851124, 209.25694216]]))

In [86]:
weights,bias = gradientDecent(X,Y,weights,bias,epochs,alpha,9)

In [87]:
weights,bias

(array([[ -7.38065149,   6.96218337,   5.45242821,   1.94047445,
         -13.22647721,   0.70527009,  -4.08404607,   6.59377005,
           7.51304124]]),
 52.12187274910413)

In [88]:
np.matmul(X[0],weights.T)+bias

array([294.81382932])

In [89]:
X[0],weights.T

(array([38., 84.,  2., 90., 32., 66., 81.,  6., 56.]),
 array([[ -7.38065149],
        [  6.96218337],
        [  5.45242821],
        [  1.94047445],
        [-13.22647721],
        [  0.70527009],
        [ -4.08404607],
        [  6.59377005],
        [  7.51304124]]))